services:
  app-front:
    build: ./app-front
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - reports-service
    networks:
      - app-network
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  auth-service:
    build: ./auth-service
    networks:
      - app-network
    volumes:
      - ./auth-service:/app
      - /app/node_modules

  reports-service:
    build: ./reports-service
    networks:
      - app-network
    volumes:
      - ./reports-service:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge