services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - reports-service
    networks:
      - app-network
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_DB: ${AUTH_DB}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${AUTH_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: auth-service
    volumes:
      - ./auth-service:/app
      - /app/node_modules
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_NAME: ${AUTH_DB}
      DB_USER: ${AUTH_DB_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  report-db:
    image: postgres:15
    container_name: report-db
    environment:
      POSTGRES_DB: ${REPORT_DB}
      POSTGRES_USER: ${REPORT_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - reportdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d ${REPORT_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  reports-service:
    build: ./reports-service
    container_name: reports-service
    volumes:
      - ./reports-service:/app
      - /app/node_modules
    depends_on:
      report-db:
        condition: service_healthy
    networks:
      - app-network
    environment:
      DB_HOST: report-db
      DB_PORT: 5432
      DB_NAME: ${REPORT_DB}
      DB_USER: ${REPORT_DB_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - app-network

volumes:
  reportdata:
  pgdata:


networks:
  app-network:
    driver: bridge
    external: true
