version: "3.8"

services:
  app-front:
    build: ./app-front
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
      - reports-service
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    ports:
      - "8001:8001"
    networks:
      - app-network

  reports-service:
    build: ./reports-service
    ports:
      - "8002:8002"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge