version: '3.8'

services:
  report-db:
    image: postgres:15
    container_name: report-db
    environment:
      POSTGRES_DB: reportdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5435:5432"
    volumes:
      - reportdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d reportdb" ]
      interval: 5s
      timeout: 5s
      retries: 5

  report-service:
    build: .
    container_name: report-service
    depends_on:
      report-db:
        condition: service_healthy
    ports:
      - "8002:8002"
    environment:
      DB_HOST: report-db # ✅ this must match service name
      DB_PORT: 5432
      DB_NAME: reportdb
      DB_USER: postgres
      DB_PASS: yourpassword

volumes:
  reportdata:
